# Generated by Django 4.2.7 on 2025-07-10 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('infrastructure', '0001_initial'),
        ('competition', '0001_initial'),
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Goles Local')),
                ('away_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Goles Visitante')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('live', 'En Vivo'), ('finished', 'Finalizado'), ('suspended', 'Suspendido'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('match_duration', models.PositiveIntegerField(default=90, verbose_name='Duración (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='officials.referee', verbose_name='Árbitro')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competition.stage', verbose_name='Fase')),
                ('team_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='clubs.team', verbose_name='Equipo Visitante')),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='clubs.team', verbose_name='Equipo Local')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='infrastructure.venue', verbose_name='Cancha')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Minuto')),
                ('event_type', models.CharField(choices=[('goal', 'Gol'), ('yellow_card', 'Tarjeta Amarilla'), ('red_card', 'Tarjeta Roja'), ('substitution', 'Sustitución'), ('penalty', 'Penal'), ('own_goal', 'Autogol')], max_length=20, verbose_name='Tipo de Evento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match', verbose_name='Partido')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='clubs.player', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Evento del Partido',
                'verbose_name_plural': 'Eventos del Partido',
                'ordering': ['match', 'minute'],
            },
        ),
    ]
