# Generated by Django 4.2.7 on 2025-07-10 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Cancha')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('field_type', models.CharField(choices=[('grass', 'Césped Natural'), ('artificial', 'Césped Artificial'), ('concrete', 'Concreto')], default='artificial', max_length=50, verbose_name='Tipo de Cancha')),
                ('has_lighting', models.BooleanField(default=True, verbose_name='Tiene Iluminación')),
                ('has_changing_rooms', models.BooleanField(default=True, verbose_name='Tiene Vestuarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['name'],
            },
        ),
    ]
