# Generated by Django 4.2.7 on 2025-07-10 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Torneo')),
                ('season_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)], verbose_name='Año de Temporada')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-season_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Fase')),
                ('stage_type', models.CharField(choices=[('group', 'Fase de Grupos'), ('round16', 'Octavos de Final'), ('quarter', 'Cuartos de Final'), ('semi', 'Semifinales'), ('final', 'Final')], default='group', max_length=20)),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='competition.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['tournament', 'order'],
                'unique_together': {('tournament', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Grupo')),
                ('max_teams', models.PositiveIntegerField(default=6, verbose_name='Máximo de Equipos')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competition.stage', verbose_name='Fase')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['stage', 'name'],
                'unique_together': {('stage', 'name')},
            },
        ),
    ]
