# Generated by Django 4.2.7 on 2025-07-10 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0, verbose_name='Partidos Jugados')),
                ('won', models.PositiveIntegerField(default=0, verbose_name='Ganados')),
                ('drawn', models.PositiveIntegerField(default=0, verbose_name='Empatados')),
                ('lost', models.PositiveIntegerField(default=0, verbose_name='Perdidos')),
                ('goals_for', models.PositiveIntegerField(default=0, verbose_name='Goles a Favor')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='Goles en Contra')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puntos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='clubs.team', verbose_name='Equipo')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competition.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Tabla de Posiciones',
                'ordering': ['-points', '-goals_for', 'goals_against'],
                'unique_together': {('team', 'tournament')},
            },
        ),
    ]
